CREATE TABLE listings (
    id TEXT,
    name TEXT,
    host_id TEXT,
    host_name TEXT,
    host_since TEXT,
    host_is_superhost TEXT,
    host_listings_count TEXT,
    neighbourhood_cleansed TEXT,
    neighbourhood_group_cleansed TEXT,
    latitude TEXT,
    longitude TEXT,
    property_type TEXT,
    room_type TEXT,
    accommodates TEXT,
    bathrooms TEXT,
    bedrooms TEXT,
    beds TEXT,
    price TEXT,
    minimum_nights TEXT,
    maximum_nights TEXT,
    availability_365 TEXT,
    number_of_reviews TEXT,
    number_of_reviews_ltm TEXT,
    estimated_occupancy_l365d TEXT,
    estimated_revenue_l365d TEXT,
    first_review TEXT,
    last_review TEXT,
    review_scores_rating TEXT,
    review_scores_cleanliness TEXT,
    review_scores_location TEXT,
    review_scores_value TEXT,
    instant_bookable TEXT,
    calculated_host_listings_count TEXT
);

CREATE TABLE reviews (
    id TEXT,
    listing_id TEXT,
    review_date TEXT,
    reviewer_id TEXT,
    reviewer_name TEXT,
);
